# Form implementation generated from reading ui file 'C:\Users\khmel\Desktop\Projects\patients_record\UI\addRecordWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddingRecord(object):
    def setupUi(self, AddingRecord):
        AddingRecord.setObjectName("AddingRecord")
        AddingRecord.resize(400, 108)
        self.pushButton = QtWidgets.QPushButton(parent=AddingRecord)
        self.pushButton.setGeometry(QtCore.QRect(250, 80, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(parent=AddingRecord)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 91, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.spec_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.spec_comboBox.setObjectName("spec_comboBox")
        self.verticalLayout_4.addWidget(self.spec_comboBox)
        self.layoutWidget1 = QtWidgets.QWidget(parent=AddingRecord)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 20, 71, 46))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.layoutWidget1)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.layoutWidget2 = QtWidgets.QWidget(parent=AddingRecord)
        self.layoutWidget2.setGeometry(QtCore.QRect(290, 20, 71, 46))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.time_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget2)
        self.time_comboBox.setObjectName("time_comboBox")
        self.verticalLayout_2.addWidget(self.time_comboBox)
        self.layoutWidget3 = QtWidgets.QWidget(parent=AddingRecord)
        self.layoutWidget3.setGeometry(QtCore.QRect(120, 20, 71, 46))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.doc_comboBox = QtWidgets.QComboBox(parent=self.layoutWidget3)
        self.doc_comboBox.setObjectName("doc_comboBox")
        self.verticalLayout_3.addWidget(self.doc_comboBox)

        self.retranslateUi(AddingRecord)
        QtCore.QMetaObject.connectSlotsByName(AddingRecord)

    def retranslateUi(self, AddingRecord):
        _translate = QtCore.QCoreApplication.translate
        AddingRecord.setWindowTitle(_translate("AddingRecord", "Добавление записи"))
        self.pushButton.setText(_translate("AddingRecord", "Добавить"))
        self.label_4.setText(_translate("AddingRecord", "Специальность"))
        self.label_3.setText(_translate("AddingRecord", "Пациент"))
        self.label_2.setText(_translate("AddingRecord", "Время"))
        self.label.setText(_translate("AddingRecord", "Врач"))
