# Form implementation generated from reading ui file 'C:\Users\khmel\Desktop\Projects\patients_record\UI\deleteWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteWindow(object):
    def setupUi(self, DeleteWindow):
        DeleteWindow.setObjectName("DeleteWindow")
        DeleteWindow.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(parent=DeleteWindow)
        self.pushButton.setGeometry(QtCore.QRect(200, 260, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(parent=DeleteWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 258, 216))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.doctors_list = QtWidgets.QListView(parent=self.layoutWidget)
        self.doctors_list.setObjectName("doctors_list")
        self.verticalLayout.addWidget(self.doctors_list)

        self.retranslateUi(DeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteWindow)

    def retranslateUi(self, DeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteWindow.setWindowTitle(_translate("DeleteWindow", "Удаление врача"))
        self.pushButton.setText(_translate("DeleteWindow", "Удалить"))
        self.label.setText(_translate("DeleteWindow", "Список Врачей"))
