# Form implementation generated from reading ui file 'C:\Users\khmel\Desktop\Projects\patients_record\UI\addRecordWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddingRecord(object):
    def setupUi(self, AddingRecord):
        AddingRecord.setObjectName("AddingRecord")
        AddingRecord.resize(616, 96)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(AddingRecord)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=AddingRecord)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.spec_comboBox = QtWidgets.QComboBox(parent=AddingRecord)
        self.spec_comboBox.setObjectName("spec_comboBox")
        self.verticalLayout_4.addWidget(self.spec_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=AddingRecord)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.doc_comboBox = QtWidgets.QComboBox(parent=AddingRecord)
        self.doc_comboBox.setObjectName("doc_comboBox")
        self.verticalLayout_3.addWidget(self.doc_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=AddingRecord)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.time_comboBox = QtWidgets.QComboBox(parent=AddingRecord)
        self.time_comboBox.setObjectName("time_comboBox")
        self.verticalLayout_2.addWidget(self.time_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=AddingRecord)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox_3 = QtWidgets.QComboBox(parent=AddingRecord)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(parent=AddingRecord)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)

        self.retranslateUi(AddingRecord)
        QtCore.QMetaObject.connectSlotsByName(AddingRecord)

    def retranslateUi(self, AddingRecord):
        _translate = QtCore.QCoreApplication.translate
        AddingRecord.setWindowTitle(_translate("AddingRecord", "Добавление записи"))
        self.label_4.setText(_translate("AddingRecord", "Специальность"))
        self.label.setText(_translate("AddingRecord", "Врач"))
        self.label_2.setText(_translate("AddingRecord", "Время"))
        self.label_3.setText(_translate("AddingRecord", "Пациент"))
        self.pushButton.setText(_translate("AddingRecord", "Добавить"))
