# Form implementation generated from reading ui file 'C:\Users\khmel\Desktop\Projects\patients_record\UI\deleteRecordWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_deleteRecordWindow(object):
    def setupUi(self, deleteRecordWindow):
        deleteRecordWindow.setObjectName("deleteRecordWindow")
        deleteRecordWindow.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(parent=deleteRecordWindow)
        self.pushButton.setGeometry(QtCore.QRect(160, 250, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(parent=deleteRecordWindow)
        self.widget.setGeometry(QtCore.QRect(40, 10, 258, 216))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listView = QtWidgets.QListView(parent=self.widget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)

        self.retranslateUi(deleteRecordWindow)
        QtCore.QMetaObject.connectSlotsByName(deleteRecordWindow)

    def retranslateUi(self, deleteRecordWindow):
        _translate = QtCore.QCoreApplication.translate
        deleteRecordWindow.setWindowTitle(_translate("deleteRecordWindow", "Удаление записи"))
        self.pushButton.setText(_translate("deleteRecordWindow", "Удалить"))
        self.label.setText(_translate("deleteRecordWindow", "Список записей"))
